services:
  app:
    container_name: nextjs_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    
    # Mapping Port Aplikasi (Kiri: Laptop, Kanan: Docker)
    ports:
      - "8020:8020"
    
    # Gunakan .env
    env_file:
      - .env.local

    environment:
      # Koneksi ke Service Mongo di port ASLI (27017)
      - MONGODB_URI=mongodb://mongo:27017/tugasku
      
      # URL Login (Sesuaikan dengan Port Aplikasi)
      - NEXTAUTH_URL=https://tugas.sman1margaasih.sch.id
      
      # WAJIB: Agar Auth jalan di Docker
      - AUTH_TRUST_HOST=true
      
      - NEXTAUTH_SECRET=rahasia_sekolah_12345 

    depends_on:
      - mongo
    volumes:
      - ./public/uploads:/app/public/uploads

  mongo:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    # Mapping Port Database
    # Kiri (27117): Akses dari Compass Laptop
    # Kanan (27017): Port Asli Container (JANGAN UBAH YANG KANAN)
    ports:
      - "27117:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: