services:
  app:
    container_name: nextjs_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_VERSION=${NEXT_PUBLIC_VERSION}
        - NEXT_PUBLIC_PUSHER_KEY=${NEXT_PUBLIC_PUSHER_KEY}
        - NEXT_PUBLIC_PUSHER_CLUSTER=${NEXT_PUBLIC_PUSHER_CLUSTER}
        - NEXT_PUBLIC_CLOUDINARY_PRESET=${NEXT_PUBLIC_CLOUDINARY_PRESET}
        - NEXT_PUBLIC_CLOUDINARY_API_KEY=${NEXT_PUBLIC_CLOUDINARY_API_KEY}
    restart: always
    
    # Mapping Port Aplikasi (Kiri: Laptop, Kanan: Docker)
    ports:
      - "8020:8020"
    
    # Gunakan .env
    env_file:
      - .env.local

    environment:
      - MONGODB_URI=mongodb://mongo:27017/tugasku
      - REDIS_URL=redis://redis:6379
      - AUTH_TRUST_HOST=true
      # Variabel lainnya (NEXTAUTH_URL, AUTH_SECRET, dll) diambil dari .env.local
    depends_on:
      - mongo
    volumes:
      - ./public/uploads:/app/public/uploads

  mongo:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    # Mapping Port Database
    # Kiri (27117): Akses dari Compass Laptop
    # Kanan (27017): Port Asli Container (JANGAN UBAH YANG KANAN)
    ports:
      - "27117:27017"
    volumes:
      - mongodb_data:/data/db
  redis:
    container_name: redis_container
    image: redis:8.6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: # Tambahkan volume untuk redis